output_dir: 

spatial:
  #[EEA_1km, Global_EqualArea_1km, Global_WGS84_30sec]
  target_grid: "EEA_1km"
  query_res: "100m"
  bbox: None


global_temporal:
  start_year: 2018
  end_year: 2019

datasets:
  GRA:
    productTypes: ["Grassland"]

  IMP:
    productTypes: ["Imperviousness Density"]

  TCF:
    productTypes: ["Forest type"]

  CRL:
    productTypes: []

  SLF:
    productTypes: ["Small Woody Features"]

  CORINE:
    include: True
    aggregation_method: "fractional"
    format: "GeoTiff100mt"

