base_dir: "./test_outputs/"
cube_name: "micro_lake_2"

keep_raw: false

# ======================================================================
# 1. SPATIAL & TEMPORAL SELECTION
# ======================================================================
spatial:
  target_grid: "EEA"
  target_resolution: "100m"
  use_bbox: true  
  bbox:
    long_min: 5.6
    long_max: 5.8
    lat_min: 50.9
    lat_max: 51.1        

temporal:
  start_year: 2018
  start_month: 1
  end_year: 2018
  end_month: 12

resampling:
  continuous: ["average", 
               "max", 
               "min", 
               "rms"]
  discrete: "coverage" 

# ======================================================================
# 2. DATA SOURCES
# ======================================================================
sources:
  wekeo:
    enabled: true
    query_resolution: "highest" 
    datasets:
      GRA:
        include: true
        productTypes:
          - "Grassland"
      TCF: 
        include: true
        productTypes:
          - "Tree Cover Density"
          - "Forest Type"