cube_dir: "out/prototype_cubing/"
cube_name: "prototype_beInvasive_cube"

spatial:
  # select the method which should be employed
  method: "bbox"
  bbox:
    long_min: 2.392821
    long_max: 6.457763
    lat_min: 49.503853
    lat_max: 51.564469
  polygon:
    shapefile_path: "/shapefile/filename.shp"

layers:
  gbif:
    enabled: true
    type:
      occurences: true
      absences: false
    species_paths: "/directory/species_list.csv"
    taxonomic:
      highest_rank: "kingdom" #What is the highest taxonomic rank required
      lowest_rank: "species" #What is the lowest taxonomic rank required
    time:
      start_year: #Number
      end_year: #Number
      start_month: #Number between 1 and 12
      end_month: #Number between 1 and 12
    defaultCoordinateUncertainty: 1000
    cubing:
      enabled: true
      cubingGrid: "EEA"
    selection_issues: #Selection flags that need to be taken into account when selecting records
      spatial:
        hasCoordinate: true 
        zeroCoordinate: true
        invalidCoordinate: true 
        countryMismatch: true
    file:
      file_path: "out/"
      file_name: "beInvasive.csv"
      sep: "\t"

  chelsa:
    enabled: true
    chelsa_month:
      enabled: true
      time:
        start_year: 1979
        start_month: 1
        end_year: 2018
        end_month: 12
        year_range: [1979, 2020]  # Optional: for fallback or metadata only
      variables:
        include_all: true
        included: []       # Ignored if include_all is true
        excluded: []
      source:
        base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/monthly"
        version: "V.2.1"  # Optional data version tag
      metadata:
        chelsa_month:
          label: "CHELSA Monthly Climate Data"
          description: "Monthly high-resolution climate variables from CHELSA V2.1."
          year_range: "1979-2020"
          available_variables:
            clt: "Cloud cover (%)"
            cmi: "Climatic Moisture Index"
            hurs: "Relative humidity at 2m (%)"
            pet: "Potential Evapotranspiration (mm)"
            pr: "Precipitation (mm)"
            rsds: "Surface downwelling shortwave radiation (W/m²)"
            sfcWind: "Surface wind speed (m/s)"
            tas: "Mean air temperature at 2m (°C)"
            tasmax: "Daily maximum air temperature at 2m (°C)"
            tasmin: "Daily minimum air temperature at 2m (°C)"
            vpd: "Vapor Pressure Deficit (kPa)"

    chelsa_clim_ref_period:
      enabled: true
      time:
        year_range: "1981-2010"
      variables:
        include_all: true
        included: []
        excluded: []
      source:
        base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
        version: "V.2.1"
      metadata:
        chelsa_clim_ref_period:
          label: "CHELSA Climatological Reference Period"
          description: "Bioclimatic and derived climatologies for the reference period 1981–2010."
          year_range: "1981-2010"
          available_variables:
            ai: "Aridity Index"
            bio1: "Annual Mean Temperature"
            bio2: "Mean Diurnal Range"
            bio3: "Isothermality"
            bio4: "Temperature Seasonality"
            bio5: "Max Temperature of Warmest Month"
            bio6: "Min Temperature of Coldest Month"
            bio7: "Temperature Annual Range"
            bio8: "Mean Temperature of Wettest Quarter"
            bio9: "Mean Temperature of Driest Quarter"
            bio10: "Mean Temperature of Warmest Quarter"
            bio11: "Mean Temperature of Coldest Quarter"
            bio12: "Annual Precipitation"
            bio13: "Precipitation of Wettest Month"
            bio14: "Precipitation of Driest Month"
            bio15: "Precipitation Seasonality"
            bio16: "Precipitation of Wettest Quarter"
            bio17: "Precipitation of Driest Quarter"
            bio18: "Precipitation of Warmest Quarter"
            bio19: "Precipitation of Coldest Quarter"
            clt_max: "Maximum Cloud Cover"
            clt_mean: "Mean Cloud Cover"
            clt_min: "Minimum Cloud Cover"
            clt_range: "Cloud Cover Range"
            cmi_max: "Maximum Climatic Moisture Index"
            cmi_mean: "Mean Climatic Moisture Index"
            cmi_min: "Minimum Climatic Moisture Index"
            cmi_range: "Climatic Moisture Index Range"
            fcf: "Frost Change Frequency"
            fgd: "First Growing Day"
            gdd0: "Growing Degree Days (0°C base)"
            gdd5: "Growing Degree Days (5°C base)"
            gdd10: "Growing Degree Days (10°C base)"
            gddlgd0: "Low GDDs relative to long-term mean (0°C)"
            gddlgd5: "Low GDDs relative to long-term mean (5°C)"
            gddlgd10: "Low GDDs relative to long-term mean (10°C)"
            gdgfgd0: "GDD/FGD Ratio (0°C base)"
            gdgfgd5: "GDD/FGD Ratio (5°C base)"
            gdgfgd10: "GDD/FGD Ratio (10°C base)"
            gsl: "Growing Season Length"
            gsp: "Growing Season Precipitation"
            gst: "Growing Season Temperature"
            hurs_max: "Max Relative Humidity"
            hurs_mean: "Mean Relative Humidity"
            hurs_min: "Min Relative Humidity"
            hurs_range: "Relative Humidity Range"
            kg0: "Köppen-Geiger class 0"
            kg1: "Köppen-Geiger class 1"
            kg2: "Köppen-Geiger class 2"
            kg3: "Köppen-Geiger class 3"
            kg4: "Köppen-Geiger class 4"
            kg5: "Köppen-Geiger class 5"
            lgd: "Last Growing Day"
            ngd0: "Number of Growing Days (0°C)"
            ngd5: "Number of Growing Days (5°C)"
            ngd10: "Number of Growing Days (10°C)"
            npp: "Net Primary Productivity"
            pet_penman_max: "Max Penman PET"
            pet_penman_mean: "Mean Penman PET"
            pet_penman_min: "Min Penman PET"
            pet_penman_range: "Range of Penman PET"
            rsds_max: "Max Shortwave Radiation"
            rsds_mean: "Mean Shortwave Radiation"
            rsds_min: "Min Shortwave Radiation"
            rsds_range: "Shortwave Radiation Range"
            scd: "Snow Cover Duration"
            sfcWind_max: "Max Wind Speed"
            sfcWind_mean: "Mean Wind Speed"
            sfcWind_min: "Min Wind Speed"
            sfcWind_range: "Wind Speed Range"
            swb: "Soil Water Balance"
            swe: "Snow Water Equivalent"
            vpd_max: "Max Vapor Pressure Deficit"
            vpd_mean: "Mean Vapor Pressure Deficit"
            vpd_min: "Min Vapor Pressure Deficit"
            vpd_range: "Vapor Pressure Deficit Range"

    chelsa_clim_ref_month:
      enabled: true
      time:
        include_all: true 
        included: []
        excluded: []
        year_range: "1981-2010"
      variables:
        include_all: true
        included: []
        excluded: []
      source:
        base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
        version: "V.2.1"
      metadata:
        chelsa_clim_ref_month:
          label: "CHELSA Monthly Climatological Reference Data"
          description: "Monthly climatologies derived from CHELSA for the reference period 1981–2010."
          year_range: "1981-2010"
          available_variables:
            clt: "Cloud cover (%)"
            cmi: "Climatic Moisture Index"
            hurs: "Relative humidity (%)"
            pet: "Potential Evapotranspiration (mm)"
            pr: "Precipitation (mm)"
            rsds: "Surface downwelling shortwave radiation (W/m²)"
            sfcWind: "Surface wind speed (m/s)"
            tas: "Mean air temperature at 2m (°C)"
            tasmax: "Daily maximum air temperature at 2m (°C)"
            tasmin: "Daily minimum air temperature at 2m (°C)"
            vpd: "Vapor Pressure Deficit (kPa)"  

    chelsa_clim_sim_period:
      enabled: true
      time:
        include_all: true
        included: []
        excluded: []
      variables:
        include_all: true
        included: []
        excluded: []
      model:
        include_all: true
        included: []
        excluded: []
      scenario:
        include_all: true
        included: []
        excluded: []
      source:
        base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
        version: "V.2.1"
      metadata:
        chelsa_clim_sim_period:
          label: "CHELSA Climatological Simulation Periods"
          description: "Bioclimatic variables from GCM simulations over multiple future time slices."
          year_ranges:
            - "2011-2040"
            - "2041-2070"
            - "2071-2100"
          model_names:
            - "gfdl-esm4"
            - "ipsl-cm6a-lr"
            - "mpi-esm1-2-hr"
            - "mri-esm2-0"
            - "ukesm1-0-ll"
          scenario:
            - "ssp126"
            - "ssp370"
            - "ssp585"
          available_variables:
            bio1: "Annual Mean Temperature"
            bio2: "Mean Diurnal Range"
            bio3: "Isothermality"
            bio4: "Temperature Seasonality"
            bio5: "Max Temperature of Warmest Month"
            bio6: "Min Temperature of Coldest Month"
            bio7: "Temperature Annual Range"
            bio8: "Mean Temperature of Wettest Quarter"
            bio9: "Mean Temperature of Driest Quarter"
            bio10: "Mean Temperature of Warmest Quarter"
            bio11: "Mean Temperature of Coldest Quarter"
            bio12: "Annual Precipitation"
            bio13: "Precipitation of Wettest Month"
            bio14: "Precipitation of Driest Month"
            bio15: "Precipitation Seasonality"
            bio16: "Precipitation of Wettest Quarter"
            bio17: "Precipitation of Driest Quarter"
            bio18: "Precipitation of Warmest Quarter"
            bio19: "Precipitation of Coldest Quarter"
            fcf: "Frost Change Frequency"
            fgd: "First Growing Day"
            gdd0: "Growing Degree Days (0°C base)"
            gdd5: "Growing Degree Days (5°C base)"
            gdd10: "Growing Degree Days (10°C base)"
            gddlgd0: "Low GDDs relative to long-term mean (0°C)"
            gddlgd5: "Low GDDs relative to long-term mean (5°C)"
            gddlgd10: "Low GDDs relative to long-term mean (10°C)"
            gdgfgd0: "GDD/FGD Ratio (0°C base)"
            gdgfgd5: "GDD/FGD Ratio (5°C base)"
            gdgfgd10: "GDD/FGD Ratio (10°C base)"
            gsl: "Growing Season Length"
            gsp: "Growing Season Precipitation"
            gst: "Growing Season Temperature"
            kg0: "Köppen-Geiger Class 0"
            kg1: "Köppen-Geiger Class 1"
            kg2: "Köppen-Geiger Class 2"
            kg3: "Köppen-Geiger Class 3"
            kg4: "Köppen-Geiger Class 4"
            kg5: "Köppen-Geiger Class 5"
            lgd: "Last Growing Day"
            ngd0: "Number of Growing Days (0°C)"
            ngd5: "Number of Growing Days (5°C)"
            ngd10: "Number of Growing Days (10°C)"
            npp: "Net Primary Productivity"
            scd: "Snow Cover Duration"
            swe: "Snow Water Equivalent"
    
    chelsa_clim_sim_month:
      enabled: true
      time:
        year_ranges:
          include_all: true
          included: []
          excluded: []
        months:
          include_all: true 
          included: []
          excluded: []
      variables:
        include_all: true
        included: []
        excluded: []
      model:
        include_all: true
        included: []
        excluded: []
      scenario:
        include_all: true
        included: []
        excluded: []
      source:
        base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
        version: "V.2.1"
    metadata:
    chelsa_clim_sim_month:
      label: "CHELSA Monthly Simulated Climate Variables"
      description: "Monthly climate simulations from GCM models under different climate scenarios."
      year_ranges:
        - "2011-2040"
        - "2041-2070"
        - "2071-2100"
      model_names:
        - "gfdl-esm4"
        - "ipsl-cm6a-lr"
        - "mpi-esm1-2-hr"
        - "mri-esm2-0"
        - "ukesm1-0-ll"
      scenario:
        - "ssp126"
        - "ssp370"
        - "ssp585"
      available_variables:
        pr: "Precipitation (mm)"
        tas: "Mean air temperature at 2m (°C)"
        tasmax: "Daily maximum air temperature at 2m (°C)"
        tasmin: "Daily minimum air temperature at 2m (°C)"