spatial:
  # select the method which should be employed
  method: "bbox"
  bbox:
    long_min: 0
    long_max: 0
    lat_min: 0
    lat_max: 0
  polygon:
    shapefile_path: "/shapefile/filename.shp"

layers:
  chelsa_month:
    enabled: true
    time:
      start_year: 1979
      start_month: 1
      end_year: 2020
      end_month: 12
      year_range: [1979, 2020]  # Optional: for fallback or metadata only
    variables:
      include_all: true
      included: []       # Ignored if include_all is true
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/monthly"
      version: "V.2.1"  # Optional data version tag

  chelsa_clim_ref_period:
    enabled: true
    time:
      year_range: "1981-2010"
    variables:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
      version: "V.2.1"
  
  chelsa_clim_ref_month:
    enabled: true
    time:
      include_all: true 
      months: []
      year_range: "1981-2010"
    variables:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
      version: "V.2.1"
  
  chelsa_clim_sim_period:
    enabled: true
    time:
      include_all: true
      included: []
      excluded: []
    variables:
      include_all: true
      included: []
      excluded: []
    model:
      include_all: true
      included: []
      excluded: []
    ensemble_member:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
      version: "V.2.1"

  chelsa_clim_sim_month:
    enabled: true
    time:
      year_ranges:
        include_all: true
        included: []
        excluded: []
      months:
        include_all: true 
        included: []
        excluded: []
    variables:
      include_all: true
      included: []
      excluded: []
    model:
      include_all: true
      included: []
      excluded: []
    ensemble_member:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
      version: "V.2.1"