spatial:
  # select the method which should be employed
  method: "bbox"
  bbox:
    long_min: 4.171371
    long_max: 4.743004
    lat_min: 50.684060
    lat_max: 50.877911
  polygon:
    shapefile_path: "/shapefile/filename.shp"

layers:
  chelsa_month:
    enabled: true
    time:
      start_year: 1980
      start_month: 1
      end_year: 1980
      end_month: 12
      year_range: [1979, 2020]  # Optional: for fallback or metadata only
    variables:
      include_all: true
      included: []       # Ignored if include_all is true
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/monthly"
      version: "V.2.1"  # Optional data version tag

  chelsa_clim_ref_period:
    enabled: true
    time:
      year_range: "1981-2010"
    variables:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
      version: "V.2.1"
  
  chelsa_clim_ref_month:
    enabled: true
    time:
      include_all: false 
      included: [1,2]
      excluded: []
      year_range: "1981-2010"
    variables:
      include_all: true
      included: []
      excluded: []
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies/1981-2010"
      version: "V.2.1"
  
  chelsa_clim_sim_period:
    enabled: true
    time:
      include_all: false
      included: ["2011-2040", "2041-2070"]
      excluded: []
    variables:
      include_all: true
      included: []
      excluded: []
    model:
      include_all: false
      included: ["gfdl-esm4", "mpi-esm1-2-hr"]
      excluded: []
    ensemble_member:
      include_all: false
      included: []
      excluded: ["ssp585"]
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
      version: "V.2.1"

  chelsa_clim_sim_month:
    enabled: true
    time:
      year_ranges:
        include_all: false
        included: ["2011-2040", "2041-2070"]
        excluded: []
      months:
        include_all: false 
        included: [1]
        excluded: []
    variables:
      include_all: true
      included: []
      excluded: []
    model:
      include_all: false
      included: ["ipsl-cm6a-lr", "ukesm1-0-ll"]
      excluded: []
    ensemble_member:
      include_all: false
      included: []
      excluded: ["ssp370"]
    source:
      base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/climatologies"
      version: "V.2.1"