"""
Implementation of distribution metrics during the resampling of categorical data. GDAL does not accept 
custom functions so we can investigate a work around where we write custom out of core processing of tiles
by chunking the dataset and passing our custom functions over it

--------------------------------

Here is a comprehensive summary of our architectural deep dive into advanced spatial texture metrics, the inherent engineering challenges, and the modern solutions to overcome them.
1. The Texture Metrics Overview

When upgrading a Data Lake from basic aggregations to advanced ecological structure, the mathematical approach splits strictly based on the data type:

A. Discrete (Categorical) Scenarios
Used for layers like Forest Type or Land Cover.

    Shannon Entropy: Measures landscape diversity (e.g., is the pixel 100% forest, or a mix of forest, water, and grass?). Advantage: Can be calculated downstream purely from your 100m fractional coverage layers.

    Gray Level Co-occurrence Matrix (GLCM): Measures spatial arrangement and texture (e.g., are the trees clumped or dispersed?). Constraint: Must be calculated using a moving window directly on the raw, high-resolution (10m) data.

B. Continuous Scenarios
Used for scalar fields like Tree Cover Density or Elevation.

    Standard Deviation / Variance: The simplest measure of continuous heterogeneity. Easily implemented in GDAL Warp alongside your average and max statistics.

    Discrete Wavelets (DWT): Decomposes the image to explicitly capture horizontal, vertical, and diagonal roughness.

    Gradient Vector Fields (HOG & VRM): Treats the continuous surface as a 2D topographic map, calculating a vector (magnitude and angle) for every pixel.

        Magnitude Distribution: Tells you the physical roughness (smooth slope vs. chaotic canopy).

        Angle Distribution (Circular Variance): Tells you the directional bias (e.g., parallel ridges vs. uniform bumpy canopy).

2. The Core Issues: Why Texture Breaks Standard Pipelines

Calculating texture is easy; storing and scaling it is mathematically treacherous.

    The Modifiable Areal Unit Problem (MAUP): Texture is strictly scale-dependent. You absolutely cannot calculate a texture metric at 10m and then mathematically average those values to get the 100m texture. The average of "local texture" does not equal "macro texture."

    The COG Pyramid Trap: Cloud Optimized GeoTIFFs (COGs) automatically build multi-resolution overviews using linear math (like averaging). If you store a 10m GLCM layer in a COG, the 100m overview generated by GDAL will be mathematically invalid garbage.

    Reprojection Distortion: You cannot warp or reproject a texture layer. If you calculate GLCM or Gradient vectors on a WGS84 grid and then reproject to EPSG:3035, the resampling interpolation will blur and destroy the directional relationships of the texture matrix.

3. The Resolution: "Compute-on-the-Fly" Architecture

To resolve the paradox of needing multi-resolution, multi-grid texture without violating spatial mathematics (or buying petabytes of hard drives), the pipeline architecture must shift from Storage-Heavy to Compute-Heavy.

The Golden Rules of the New Architecture:

    Warp First, Calculate Second: Always reproject the raw 10m data to your master grid (e.g., EEA using nearest neighbor) before applying any texture algorithms.

    Store Only the Foundation: Store only the perfectly aligned, foundational 10m data (like Tree Cover Density or Forest Type) using aggressive compression (like LERC for continuous data). Do not pre-calculate and store texture layers.

    Lazy Evaluation (Dask/Zarr): When a user requests a 1km Continuous Roughness layer, your system dynamically streams the raw 10m chunks into RAM, applies the gradient math or GLCM moving window on the fly using xarray and dask, and delivers the result.

This approach guarantees that every texture derivative generated by your Data Lake is mathematically pure, scaled correctly to the exact user-requested bounding box, and costs you virtually nothing in hard drive space.

Would you like to map out the specific Python functions required to build this lazy Dask computation graph, or should we focus on finalizing the CodeMeta provenance tracking for the layers we have already successfully generated?
"""

import numpy as np
from scipy.stats import entropy
from skimage.util import view_as_blocks
from skimage.feature import graycomatrix, graycoprops

def calculate_block_entropy(high_res_array: np.ndarray, downsample_factor: int = 10, nodata_val: int = 255) -> np.ndarray:
    """
    Calculates Shannon Entropy for categorical data.
    Takes a high-res array and compresses it by the downsample_factor.
    """
    # Break array into e.g., 10x10 blocks
    blocks = view_as_blocks(high_res_array, block_shape=(downsample_factor, downsample_factor))
    flat_blocks = blocks.reshape(blocks.shape[0], blocks.shape[1], -1)
    
    new_y, new_x, _ = flat_blocks.shape
    entropy_grid = np.zeros((new_y, new_x), dtype=np.float32)
    
    for i in range(new_y):
        for j in range(new_x):
            block_pixels = flat_blocks[i, j, :]
            
            # Ignore NoData
            valid_pixels = block_pixels[block_pixels != nodata_val]
            if len(valid_pixels) == 0:
                entropy_grid[i, j] = np.nan
                continue
                
            # Calculate Entropy
            _, counts = np.unique(valid_pixels, return_counts=True)
            entropy_grid[i, j] = entropy(counts, base=2)
            
    return entropy_grid


def calculate_glcm_homogeneity(high_res_array: np.ndarray, downsample_factor: int = 10, nodata_val: int = 255) -> np.ndarray:
    """
    Calculates GLCM Homogeneity.
    """
    # GLCM strictly requires positive integers (uint8)
    high_res_array = high_res_array.astype(np.uint8) 
    
    blocks = view_as_blocks(high_res_array, block_shape=(downsample_factor, downsample_factor))
    new_y, new_x = blocks.shape[0], blocks.shape[1]
    
    homogeneity_grid = np.zeros((new_y, new_x), dtype=np.float32)
    
    for i in range(new_y):
        for j in range(new_x):
            block = blocks[i, j, :, :]
            
            # If the entire block is NoData, skip calculation
            if np.all(block == nodata_val):
                homogeneity_grid[i, j] = np.nan
                continue
                
            # Calculate Co-occurrence Matrix (1 pixel away, horizontal)
            glcm = graycomatrix(block, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
            homogeneity_grid[i, j] = graycoprops(glcm, 'homogeneity')[0, 0]
            
    return homogeneity_grid

import rasterio
from rasterio.windows import Window
from rasterio.transform import Affine
import math
import logging

def process_texture_out_of_core(
    input_path: str, 
    output_path: str, 
    texture_func: callable, 
    downsample_factor: int = 10, 
    chunk_size: int = 5000, 
    nodata_val: int = 255,
    logger: logging.Logger = None
):
    """
    Reads a massive raster in chunks, applies a texture metric function to compress it,
    and writes the result sequentially to a new Cloud Optimized GeoTIFF.

    Parameters
    ----------
    input_path : str
        Path to the raw high-resolution raster or VRT.
    output_path : str
        Path to save the new low-resolution texture COG.
    texture_func : callable
        The function to apply (e.g., calculate_block_entropy).
    downsample_factor : int
        The resolution reduction factor (e.g., 10m to 100m = 10).
    chunk_size : int
        How many high-res pixels to process in memory at once (must be a multiple of downsample_factor).
    """
    if chunk_size % downsample_factor != 0:
        raise ValueError("chunk_size must be perfectly divisible by downsample_factor.")

    with rasterio.open(input_path) as src:
        # Calculate new dimensions
        new_width = src.width // downsample_factor
        new_height = src.height // downsample_factor
        
        # Scale the affine transform matrix mathematically
        new_transform = src.transform * Affine.scale(downsample_factor)
        
        # Build the profile for the output Cloud Optimized GeoTIFF
        profile = src.profile.copy()
        profile.update({
            'driver': 'COG',
            'height': new_height,
            'width': new_width,
            'transform': new_transform,
            'dtype': 'float32',
            'nodata': np.nan,
            'compress': 'deflate'
        })
        
        if logger:
            logger.info(f"Starting chunked texture processing. Target: {new_width}x{new_height} pixels.")
        
        with rasterio.open(output_path, 'w', **profile) as dst:
            
            # Loop through the massive file in RAM-safe chunks
            for row in range(0, src.height, chunk_size):
                for col in range(0, src.width, chunk_size):
                    
                    # Prevent chunks from hanging off the edge of the map
                    current_chunk_height = min(chunk_size, src.height - row)
                    current_chunk_width = min(chunk_size, src.width - col)
                    
                    # Trim edges to ensure they are cleanly divisible by the downsample factor
                    current_chunk_height -= current_chunk_height % downsample_factor
                    current_chunk_width -= current_chunk_width % downsample_factor
                    
                    if current_chunk_height == 0 or current_chunk_width == 0:
                        continue
                        
                    # 1. Read the high-res chunk into RAM
                    read_window = Window(col, row, current_chunk_width, current_chunk_height)
                    data_chunk = src.read(1, window=read_window)
                    
                    # 2. Apply the texture math (Compresses the chunk)
                    compacted_chunk = texture_func(data_chunk, downsample_factor=downsample_factor, nodata_val=nodata_val)
                    
                    # 3. Write the compacted chunk out to the hard drive
                    write_window = Window(
                        col // downsample_factor, 
                        row // downsample_factor, 
                        current_chunk_width // downsample_factor, 
                        current_chunk_height // downsample_factor
                    )
                    dst.write(compacted_chunk, 1, window=write_window)
                    
        if logger:
            logger.info(f"Successfully generated texture COG: {output_path}")