    def _validate_config_products(
            self,
            recipe: Dict[str, Any], 
            inventory_df: pd.DataFrame, 
            logger: Optional[logging.Logger] = None
            ) -> bool:
        """
        Validates user-requested WEkEO product types against the ground-truth API inventory.

        This method inspects the 'sources' block of the provided recipe to ensure that 
        every product requested under the WEkEO category exists within the inventory 
        database. It serves as a pre-flight safety check to prevent invalid API calls.

        Parameters
        ----------
        recipe : dict
            The standardized execution recipe dictionary generated by 
            `generate_cube_recipe`. It must contain a 'sources' key.
        inventory_df : pd.DataFrame
            The ground-truth inventory DataFrame containing a 'productType' column.
        logger : logging.Logger, optional
            The logger instance to use for recording validation successes or warnings. 
            Default is None.

        Returns
        -------
        is_valid : bool
            True if all requested products exist in the inventory or if WEkEO is 
            disabled; False otherwise.

        Notes
        -----
        If the 'wekeo' source is disabled in the recipe, this function returns True 
        by default and skips inventory cross-referencing.
        """
        is_valid = True
        
        # Extract the wekeo configuration from the recipe's source block
        wekeo_config = recipe.get('sources', {}).get('wekeo', {})
        
        if not wekeo_config.get('enabled', False):
            log_execution(logger, "WEkEO pipeline is disabled in recipe. Skipping validation.", logging.INFO)
            return True
            
        datasets_config = wekeo_config.get('datasets', {})
        available_products = set(inventory_df['productType'].dropna().unique())
        
        for category, cat_config in datasets_config.items():
            if not cat_config or not cat_config.get('include', False):
                continue
                
            requested_products = cat_config.get('productTypes', [])
            
            for product in requested_products:
                if product not in available_products:
                    log_execution(
                        logger, 
                        f"Mismatch in [{category}]: Requested product '{product}' was not found in the inventory.", 
                        logging.WARNING
                    )
                    is_valid = False
                    
        if is_valid:
            log_execution(logger, "Validation passed: All requested productTypes match the inventory.", logging.INFO)
            
        return is_valid

    def intersect_config_with_dataframe(
        self,
        recipe: Dict[str, Any],
        inventory_csv_path: str,
        logger: Optional[logging.Logger] = None
        ) -> List[Dict[str, Any]]:
        """
        Generates an execution queue of valid WEkEO API queries based on the cube recipe.

        This orchestrator parses the temporal, spatial, and source constraints 
        defined in the recipe and cross-references them with the local inventory CSV. 
        It produces a list of payload dictionaries ready for the HDA API client.

        Parameters
        ----------
        recipe : dict
            The standardized execution recipe dictionary containing 'temporal', 
            'spatial', and 'sources' parameters.
        inventory_csv_path : str
            The file path to the ground-truth inventory CSV.
        logger : logging.Logger, optional
            The logger instance for recording progress and skipped data warnings. 
            Default is None.

        Returns
        -------
        execution_queue : list of dict
            A list of fully formed WEkEO HDA API query dictionaries.

        Raises
        ------
        ValueError
            If the recipe fails the product validation check against the inventory.

        Notes
        -----
        This function automatically converts the dictionary-style bounding box 
        stored in the recipe into the flat [min_lon, min_lat, max_lon, max_lat] 
        list format required by the WEkEO query generator.
        """
        # 1. Load the ground truth
        df = pd.read_csv(inventory_csv_path)
        
        # 2. VALIDATE USING THE RECIPE
        if not self._validate_config_products(recipe, df, logger):
            raise ValueError("Recipe validation failed: requested products not in inventory. Check logs.")
        
        # 3. Extract Constraints from Recipe
        # Temporal
        temp_cfg = recipe.get('temporal', {})
        start_year = temp_cfg.get('start_year')
        end_year = temp_cfg.get('end_year')
        
        # Spatial (Target resolution is still needed for inventory filtering)
        # We fetch this from raw_config as it's an inventory filter parameter, not a grid spec.
        target_res = recipe.get('raw_config', {}).get('spatial', {}).get('target_resolution', '100m')
        
        # Bounding Box Conversion (Dict -> List)
        user_bbox = None
        bbox_dict = recipe.get('spatial', {}).get('bbox')
        if bbox_dict:
            user_bbox = [
                bbox_dict['long_min'], 
                bbox_dict['lat_min'], 
                bbox_dict['long_max'], 
                bbox_dict['lat_max']
            ]
            
        execution_queue = []
        temporal_df = df[(df['year'] >= start_year) & (df['year'] <= end_year)]
        
        # Access datasets specifically from the wekeo source in the recipe
        datasets_config = recipe.get('sources', {}).get('wekeo', {}).get('datasets', {})
        
        for category, cat_config in datasets_config.items():
            if not cat_config or not cat_config.get('include', False): 
                continue
                
            # Handle "Format-based" (e.g., CORINE)
            if 'format' in cat_config:
                target_format = cat_config.get('format')
                strict_df = temporal_df[(temporal_df['category'] == category) & 
                                        (temporal_df['format'] == target_format)]
                
                if strict_df.empty:
                    log_execution(logger, f"Skipped {category}: No '{target_format}' data for {start_year}-{end_year}.", logging.WARNING)
                    continue
                
                for _, row in strict_df.iterrows():
                    query = generate_wekeo_query(
                        dataset_id=row['dataset_id'],
                        product_type=row['productType'],
                        data_format=target_format,
                        bbox=user_bbox
                    )
                    execution_queue.append(query)
                    log_execution(logger, f"Queued: {row['productType']} ({row['year']}) at {target_format}", logging.INFO)

            # Handle "Resolution-based" (e.g., HRL)
            elif 'productTypes' in cat_config:
                for product in cat_config['productTypes']:
                    strict_df = temporal_df[(temporal_df['productType'] == product) & 
                                            (temporal_df['resolution'] == target_res)]
                    
                    if strict_df.empty:
                        log_execution(logger, f"Skipped '{product}': No '{target_res}' data for {start_year}-{end_year}.", logging.WARNING)
                        continue
                        
                    for year in sorted(strict_df['year'].unique()):
                        dataset_id = strict_df[strict_df['year'] == year]['dataset_id'].iloc[0]
                        query = generate_wekeo_query(
                            dataset_id=dataset_id,
                            product_type=product,
                            year=str(year),
                            resolution=target_res,
                            bbox=user_bbox
                        )
                        execution_queue.append(query)
                        log_execution(logger, f"Queued: {product} ({year}) at {target_res}", logging.INFO)
                    
        return execution_queue

def calculate_fractional_coverages(
        self,
        ds: Union[xr.DataArray, xr.Dataset, str], 
        grid_name: str, 
        output_dir: str, 
        class_values: Optional[list[int]] = None,
        logger: Optional[logging.Logger] = None
    ) -> xr.Dataset:
        """
        Calculates the fractional coverage of categorical classes snapped to a target grid.

        Because categorical data (like land cover) cannot be accurately resampled directly 
        using continuous algorithms, this method utilizes a memory-efficient binary masking 
        technique. It iterates through each unique categorical class, isolates it as a binary 
        presence/absence mask at the native resolution, and streams that mask through an 
        out-of-core spatial warp using an 'average' resampling algorithm. This translates 
        discrete pixels into mathematically precise fractional percentages per target pixel.

        Parameters
        ----------
        ds : xarray.DataArray, xarray.Dataset, or str
            The high-resolution categorical input data. Can be a pre-loaded xarray object, 
            or a string path to a file (e.g., a .vrt or .tif), which will be lazy-loaded.
        grid_name : str
            The key of the target grid defined in the class `GRID_REGISTRY`.
        output_dir : str
            The directory where the individual fractional `.tif` files will be saved. 
        class_values : list of int, optional
            A specific list of integer classes to process. If ``None``, the function 
            will pull the array into memory to automatically discover unique values. 
        logger : logging.Logger, optional
            The logger instance to use for recording execution messages. Default is ``None``.

        Returns
        -------
        xarray.Dataset
            A unified Dataset containing lazy references to all generated fractional 
            coverage layers. Each data variable is cleanly formatted and named as 
            `fraction_class_{N}`.
        """
        import os
        import numpy as np
        import xarray as xr
        import rioxarray
        from pathlib import Path

        # Ensure the output directory exists before we start generating files
        os.makedirs(output_dir, exist_ok=True)
        
        # --- FIX: Handle String/Path inputs by lazy-loading them ---
        if isinstance(ds, (str, Path)):
            log_execution(logger, f"Lazy-loading categorical raster from path: {ds}", logging.INFO)
            ds = rioxarray.open_rasterio(ds, chunks=True) # chunks=True prevents RAM spikes
        
        if isinstance(ds, xr.Dataset):
            var_name = list(ds.data_vars)[0]
            da = ds[var_name]
        else:
            da = ds
            
        nodata_val = da.rio.nodata

        if class_values is None:
            log_execution(logger, "Finding unique classes...", logging.INFO)
            # da.data accesses the underlying Dask array instead of forcing a NumPy array
            unique_vals = da.data.map_blocks(np.unique).compute()
            unique_vals = np.unique(unique_vals) 
            class_values = [int(v) for v in unique_vals if v not in [nodata_val, np.nan]]
            
        log_execution(logger, f"Calculating fractional coverage for {len(class_values)} classes...", logging.INFO)

        fractional_layers = {}

        for cls in class_values:
            log_execution(logger, f"\n--- Processing Class: {cls} ---", logging.INFO)
            
            # The Memory-Safe Magic Trick
            mask = (da == cls).astype(np.float32)

            if nodata_val is not None:
                mask = mask.where(da != nodata_val, np.nan)
            
            mask.rio.write_crs(da.rio.crs, inplace=True)
            mask.rio.write_transform(da.rio.transform(), inplace=True)
            mask.rio.write_nodata(np.nan, inplace=True)
            
            # Define the targeted output path for the out-of-core warp
            file_name = f"fractional_class_{int(cls)}_{grid_name}.tif"
            temp_out_path = os.path.join(output_dir, file_name)
            
            # Call the GDAL out-of-core reprojector via self
            frac_da = self.affine_reproject(
                input_data=mask, 
                output_filepath=temp_out_path, 
                grid_name=grid_name, 
                resample_keyword="average",
                logger=logger
            )
            
            # Clean up the Dataset structure
            frac_da = frac_da.squeeze().drop_vars("band", errors="ignore")
            frac_da.name = f"fraction_class_{int(cls)}"
            
            fractional_layers[frac_da.name] = frac_da

        # Combine the lazy file references into one giant Dataset
        final_ds = xr.Dataset(fractional_layers)

        log_execution(logger, f"All fractional coverages saved to '{output_dir}' and packaged.", logging.INFO)
        
        return final_ds

    def build_wekeo_datalake(
        self, 
        recipe: Dict[str, Any], 
        inventory_csv_path: str, 
        hda_client: object, 
        logger: Optional[logging.Logger] = None
    ) -> List[str]:
        """
        Backend Ingestion Engine: Downloads WEkEO data, perfectly aligns it to a 
        master spatial grid, calculates statistical derivatives, and exports everything 
        to Cloud Optimized GeoTIFFs (COGs) inside a structured Data Lake directory hierarchy.
        """
        import gc
        import os
        import sys
        import shutil

        # =================================================================
        # 1. PIPELINE LOGGER SETUP
        # =================================================================
        raw_dir = recipe["paths"]["raw_dir"]
        base_dir = recipe["paths"]["base_dir"] # Acts as the root "lake_name" directory
        
        cube_name = recipe.get('raw_config', {}).get('cube_name', 'datalake_build')
        log_filepath = os.path.join(base_dir, f"{cube_name}.log")
        
        active_logger = self._setup_pipeline_logger(logger_name=cube_name, log_filepath=log_filepath)
        
        log_execution(active_logger, f"Starting Data Lake Ingestion for: {cube_name}", logging.INFO)
        log_execution(active_logger, f"Session log path: {log_filepath}", logging.INFO)

        # =================================================================
        # 2. RECIPE PARSING & VALIDATION
        # =================================================================
        target_grid_key = recipe["spatial"]["target_grid_key"]
        resampling_config = recipe["spatial"]["resampling_strategies"]
        
        # Extract target grid and resolution for file naming (e.g., 'EEA_100m' -> 'EEA', '100m')
        try:
            target_grid, target_res = target_grid_key.split("_", 1)
        except ValueError:
            target_grid, target_res = target_grid_key, "unknown"
            
        wekeo_config = recipe["sources"].get("wekeo", {})
        if not wekeo_config.get("enabled", False):
            log_execution(active_logger, "WEkEO source disabled in recipe. Exiting.", logging.INFO)
            return []

        log_execution(active_logger, "Building API query queue from recipe...", logging.INFO)
        execution_queue = self.intersect_config_with_dataframe(recipe, inventory_csv_path, active_logger)
        
        if not execution_queue:
            log_execution(active_logger, "Execution queue is empty. Check inventory mapping.", logging.WARNING)
            return []

        generated_cogs = []

        # =================================================================
        # 3. EXECUTE THE INGESTION QUEUE
        # =================================================================
        for query in execution_queue:
            # Extract metadata for naming & folder structure
            product_type = query.get("productType", "Unknown_Product")
            clean_product = product_type.replace(' ', '_')
            year = query.get("year", "AllYears")
            
            # Extract the dataset category (e.g., 'EO:EEA:DAT:HRL:TCF' -> 'TCF')
            dataset_id = query.get("dataset_id", "")
            dataset_cat = dataset_id.split(":")[-1] if dataset_id else "UnknownDataset"
            
            safe_name = f"{clean_product}_{year}"
            log_execution(active_logger, f"\n{'='*50}\nBuilding Data Lake Layer: {safe_name}\n{'='*50}", logging.INFO)

            # A. Fetch and Build Blueprint
            download_dir = self._fetch_unpack_query(
                wekeo_query=query, hda_client=hda_client, base_dir=raw_dir, logger=active_logger
            )
            if not download_dir:
                continue

            tif_folder = os.path.join(download_dir, "tif_files")
            vrt_path = os.path.join(tif_folder, f"{safe_name}.vrt")
            if not self.build_virtual_mosaic(tif_folder, vrt_path, active_logger):
                continue

            # B. Categorical Processing (Fractional Coverage)
            if product_type in self.CATEGORICAL_CLASSES:
                discrete_strat = resampling_config.get('discrete', 'fractional')
                
                if discrete_strat == 'fractional':
                    aggr_name = "fractions"
                    
                    # Target Directory: lake_name / dataset / producttype / data_layer /
                    layer_dir = os.path.join(base_dir, dataset_cat, clean_product, aggr_name)
                    os.makedirs(layer_dir, exist_ok=True)
                    
                    # Target File: producttype_year_grid_res_aggr.tif
                    file_name = f"{clean_product}_{year}_{target_grid}_{target_res}_{aggr_name}.tif"
                    final_cog_path = os.path.join(layer_dir, file_name)
                    
                    log_execution(active_logger, "Processing as Categorical Fractional Coverages...", logging.INFO)
                    raw_classes = list(self.CATEGORICAL_CLASSES[product_type].keys())
                    target_classes = [c for c in raw_classes if c not in [48, 128, 254, 255]]
                    
                    try:
                        temp_frac_dir = os.path.join(layer_dir, "temp_fractions")
                        
                        result_xr = self.process_virtual_mosaic(
                            vrt_path=vrt_path, strategy='coverage', grid_name=target_grid_key,
                            output_dir_or_file=temp_frac_dir, logger=active_logger, class_values=target_classes
                        )
                        
                        # Export multi-band fractional dataset to the structured directory
                        self.export_to_cog(result_xr, final_cog_path, logger=active_logger)
                        generated_cogs.append(final_cog_path)
                        
                        del result_xr
                        
                        # Clean up internal temporary binary masks
                        if os.path.exists(temp_frac_dir):
                            shutil.rmtree(temp_frac_dir)
                            
                        gc.collect()
                        
                    except Exception as e:
                        log_execution(active_logger, f"Failed fractional coverage for {safe_name}: {e}", logging.ERROR)

            # C. Continuous Processing (Multiple Statistics)
            else:
                cont_stats = resampling_config.get('continuous', ['average'])
                if isinstance(cont_stats, str):
                    cont_stats = [cont_stats]

                log_execution(active_logger, f"Processing Continuous variables. Requested stats: {cont_stats}", logging.INFO)

                for stat in cont_stats:
                    aggr_name = stat.lower()
                    
                    # Target Directory: lake_name / dataset / producttype / data_layer /
                    layer_dir = os.path.join(base_dir, dataset_cat, clean_product, aggr_name)
                    os.makedirs(layer_dir, exist_ok=True)
                    
                    # Target File: producttype_year_grid_res_aggr.tif
                    file_name = f"{clean_product}_{year}_{target_grid}_{target_res}_{aggr_name}.tif"
                    final_cog_path = os.path.join(layer_dir, file_name)
                    
                    log_execution(active_logger, f"Calculating: {stat.upper()}", logging.INFO)
                    try:
                        temp_tif_path = os.path.join(layer_dir, f"temp_{file_name}")
                        
                        result_xr = self.process_virtual_mosaic(
                            vrt_path=vrt_path, strategy='reproject', grid_name=target_grid_key,
                            output_dir_or_file=temp_tif_path, logger=active_logger, resample_keyword=stat
                        )
                        
                        self.export_to_cog(result_xr, final_cog_path, logger=active_logger)
                        generated_cogs.append(final_cog_path)
                        
                        del result_xr
                        
                        # Clean up the unoptimized temporary tif file
                        if os.path.exists(temp_tif_path):
                            os.remove(temp_tif_path)
                            
                        gc.collect()
                        
                    except Exception as e:
                        log_execution(active_logger, f"Failed statistic '{stat}' for {safe_name}: {e}", logging.ERROR)

        log_execution(active_logger, "\n=== WEkEO Data Lake Ingestion Complete ===", logging.INFO)
        return generated_cogs