import geopandas as gpd
import pandas as pd
from shapely import make_valid
from shapely.geometry import MultiPolygon, MultiLineString, MultiPoint
from shapely.geometry.collection import GeometryCollection
from shapely import force_2d
import logging
from typing import Optional


class spatial_vector_engine(base_spatial_grid):
    def sanitize_geometries(
        self, 
        gdf: gpd.GeoDataFrame, 
        allowed_types: Optional[list] = None,
        logger: Optional[logging.Logger] = None) -> gpd.GeoDataFrame:
        """
        Cleans, flattens, and validates dirty vector geometries.

        Parameters
        ----------
        gdf : geopandas.GeoDataFrame
            The raw input vector dataset.
        allowed_types : list of str, optional
            If provided, strictly filters out any geometry types not in this list 
            (e.g., ['Polygon', 'MultiPolygon']). Default is None (allows all valid types).
        logger : logging.Logger, optional
            Logger instance for execution tracking.

        Returns
        -------
        geopandas.GeoDataFrame
            A pristine, strictly 2D, topologically valid GeoDataFrame.
        """
        if logger: logger.info("Initiating vector geometry sanitization...")
        
        # Purge Nulls and Empty Geometries (The Ghosts)
        initial_count = len(gdf)
        # Filter out the cells that contain non null and non empty geometries
        gdf = gdf[gdf.geometry.notnull() & ~gdf.geometry.is_empty].copy()
        dropped_empty = initial_count - len(gdf)
        if logger and dropped_empty > 0:
            logger.info(f"Dropped {dropped_empty} empty or null geometries.")

        # Force 2D Planar Geometries (Drop Z/M dimensions)
        # This prevents topology exceptions during areal intersection
        gdf.geometry = gdf.geometry.apply(force_2d)

        # Heal Invalid Topologies (The Bowties)
        invalid_mask = ~gdf.geometry.is_valid
        invalid_count = invalid_mask.sum()
        if invalid_count > 0:
            if logger: logger.info(f"Healing {invalid_count} topologically invalid geometries...")
            # Identifies geometries that are invalid and apply repairing functions
            gdf.loc[invalid_mask, 'geometry'] = gdf.loc[invalid_mask, 'geometry'].apply(make_valid)

        # Handle GeometryCollections generated by `make_valid`
        # When a polygon is fixed, it might spawn points/lines at the intersection.
        # We explode the collections and keep only the largest geometries (or specific types).
        def extract_dominant_geometry(geom):
            """
            Unpacks a GeometryCollection and extracts the geometries of the 
            highest topological dimension (Polygons > Lines > Points), 
            bundling them safely into a MultiGeometry to prevent data loss.
            """
            if not isinstance(geom, GeometryCollection):
                return geom

            parts = list(geom.geoms)
            if not parts:
                return None

            # Sort fragments into their dimensional buckets
            polygons = [p for p in parts if p.geom_type in ['Polygon', 'MultiPolygon']]
            lines = [p for p in parts if p.geom_type in ['LineString', 'MultiLineString']]
            points = [p for p in parts if p.geom_type in ['Point', 'MultiPoint']]

            # 1. If 2D shapes exist, it was originally a Polygon. Keep all polygon parts.
            if polygons:
                # If there are multiple, bundle them so no data is lost
                return MultiPolygon(polygons) if len(polygons) > 1 else polygons[0]
                
            # 2. If 1D shapes exist, it was originally a LineString (e.g., a river/road).
            elif lines:
                return MultiLineString(lines) if len(lines) > 1 else lines[0]
                
            # 3. If only 0D shapes exist, it was a Point cluster.
            elif points:
                return MultiPoint(points) if len(points) > 1 else points[0]
                
            return None

        gdf.geometry = gdf.geometry.apply(extract_dominant_geometry)
        
        # Run the empty check one more time just in case extraction resulted in empties
        gdf = gdf[gdf.geometry.notnull() & ~gdf.geometry.is_empty].copy()

        # 5. Type Enforcement (Optional)
        if allowed_types:
            type_mask = gdf.geometry.geom_type.isin(allowed_types)
            dropped_type = len(gdf) - type_mask.sum()
            gdf = gdf[type_mask].copy()
            if logger and dropped_type > 0:
                logger.info(f"Filtered out {dropped_type} geometries not matching allowed types: {allowed_types}")

        if logger: logger.info(f"Sanitization complete. Final feature count: {len(gdf)}")
        
        return gdf
    
    @staticmethod
    def _overlay_worker(
        chunk_gdf: gpd.GeoDataFrame, 
        grid_gdf: gpd.GeoDataFrame, 
        parent_spec: dict
    ) -> gpd.GeoDataFrame:
        """
        Isolated worker function for parallel spatial intersection and metric calculation.
        
        Defined as a @staticmethod so that Python's multiprocessing library can 
        easily serialize (pickle) the function and send it to isolated CPU cores 
        without dragging the entire class instance into memory.

        Parameters
        ----------
        chunk_gdf : geopandas.GeoDataFrame
            A subset of the original vector data allocated to this specific CPU core.
        grid_gdf : geopandas.GeoDataFrame
            The targeted grid mesh (either fine lines or coarse polygons) to intersect against.
        parent_spec : dict
            The master grid specification from the GRID_REGISTRY, used to calculate 
            the spatial foreign key (`parent_grid_id`).

        Returns
        -------
        geopandas.GeoDataFrame
            The normalized table of chopped geometry fragments. Contains strictly:
            [`src_uid`, `grid_id`, `parent_grid_id`, `fragment_metric`, `geometry`].
        """
        # Fast-fail if the chunk is empty (prevents GEOS errors)
        if chunk_gdf.empty:
            return gpd.GeoDataFrame()

        # The Geometric Intersection
        # We explicitly drop heavy attribute columns (keeping only src_uid and geometry)
        # before the overlay to minimize the RAM footprint during the C++ GEOS operation.
        fragments = gpd.overlay(chunk_gdf[['src_uid', 'geometry']], grid_gdf, how='intersection')
        
        if fragments.empty:
            return fragments

        # Dimensional Metric Calculation
        # We must route the fragmented geometries to the correct physical metric.
        is_poly = fragments.geom_type.isin(['Polygon', 'MultiPolygon'])
        is_line = fragments.geom_type.isin(['LineString', 'MultiLineString'])
        
        # Initialize default metric (Points keep a weight of 1.0)
        fragments['fragment_metric'] = 1.0
        
        # Calculate true Cartesian area for Polygons
        if is_poly.any():
            fragments.loc[is_poly, 'fragment_metric'] = fragments.loc[is_poly, 'geometry'].area
            
        # Calculate true Cartesian length for Lines
        if is_line.any():
            fragments.loc[is_line, 'fragment_metric'] = fragments.loc[is_line, 'geometry'].length

        # Relational DGGS Math (Calculating the Parent Grid ID)
        # Extract the absolute boundaries and resolution of the Parent Master Grid
        p_res = parent_spec['resolution']
        p_minx = parent_spec['bounds'][0]
        p_maxy = parent_spec['bounds'][3]
        
        # Calculate how many parent cells fit across the X-axis
        p_width = int(round((parent_spec['bounds'][2] - p_minx) / p_res))

        # Use the centroid of the newly chopped fragment to determine which parent it falls inside.
        centroids = fragments.geometry.centroid
        
        # Math: Col = Floor((X - MinX) / Res), Row = Floor((MaxY - Y) / Res)
        parent_cols = np.floor((centroids.x - p_minx) / p_res).astype(int)
        parent_rows = np.floor((p_maxy - centroids.y) / p_res).astype(int)
        
        # Flatten the 2D matrix coordinates (Row, Col) into a 1D relational ID
        fragments['parent_grid_id'] = (parent_rows * p_width) + parent_cols

        # Return only the essential normalized columns
        return fragments[['src_uid', 'grid_id', 'parent_grid_id', 'fragment_metric', 'geometry']]

    def transform_gdf_to_hierarchical_grid(
        self,
        source_gdf: gpd.GeoDataFrame, 
        grid: str,
        master_res: str,
        line_res: str,
        poly_res: str,
        n_jobs: int = 4,
        logger: Optional[logging.Logger] = None
    ) -> Tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
        """
        Transforms mixed vector geometries into a normalized, hierarchical spatial grid, 
        routing lines and polygons to distinct resolutions and processing them in parallel.

        Parameters
        ----------
        source_gdf : geopandas.GeoDataFrame
            The input vector dataset containing mixed geometries (Lines, Polygons).
        grid : str
            The base coordinate reference system identifier (e.g., "EEA", "Global_WGS84").
        master_res : str
            The resolution string for the overarching master grid (e.g., "10km").
        line_res : str
            The resolution string for the grid used to chop LineStrings (e.g., "10m").
        poly_res : str
            The resolution string for the grid used to chop Polygons (e.g., "1km").
        n_jobs : int, optional
            The number of parallel CPU cores to use for the intersection math. Default is 4.
        logger : logging.Logger, optional
            Logger instance for execution tracking.

        Returns
        -------
        relational_fragments : geopandas.GeoDataFrame
            A normalized table of chopped geometry fragments containing strictly:
            [`src_uid`, `grid_id`, `parent_grid_id`, `fragment_metric`, `geometry`].
        original_lookup_gdf : geopandas.GeoDataFrame
            The untouched, original geometries and all associated attribute columns, 
            linked to the fragments via the `src_uid` column.
        """
        # 1. Resolve Grid Keys
        # Dynamically map the user's string inputs to our rigid mathematical GRID_REGISTRY
        parent_grid_name = self.resolve_grid_registry_key(grid, master_res, logger)
        line_grid_name = self.resolve_grid_registry_key(grid, line_res, logger)
        poly_grid_name = self.resolve_grid_registry_key(grid, poly_res, logger)

        if logger: logger.info(f"Normalizing vector data. Polygons -> {poly_grid_name} | Lines -> {line_grid_name}")

        parent_spec = self.GRID_REGISTRY[parent_grid_name]
        target_crs = parent_spec['crs']

        # 2. Database Normalization Preparation
        # Ensure the vector data matches the exact CRS of our mathematical grids
        source_df = source_gdf.to_crs(target_crs) if source_gdf.crs != target_crs else source_gdf.copy()
        
        # Generate the primary key (src_uid) if it doesn't already exist.
        # This string acts as the relational glue between the fragments and the original data.
        if 'src_uid' not in source_df.columns:
            source_df['src_uid'] = [f"src_{i}" for i in range(len(source_df))]
        
        # Isolate the original geometries and attributes into a pristine lookup table
        original_lookup_gdf = source_df.copy()

        # 3. The Geometry Router
        # Separate the dataset by topology dimension because they require different grid resolutions
        poly_mask = source_df.geom_type.isin(['Polygon', 'MultiPolygon'])
        line_mask = source_df.geom_type.isin(['LineString', 'MultiLineString'])
        
        poly_gdf = source_df[poly_mask]
        line_gdf = source_df[line_mask]

        def _build_mesh(gdf: gpd.GeoDataFrame, grid_name: str) -> gpd.GeoDataFrame:
            """Helper to generate a targeted grid mesh strictly where data physically exists."""
            if gdf.empty: return gpd.GeoDataFrame()
            
            spec = self.GRID_REGISTRY[grid_name]
            res = spec['resolution']
            minx, miny, maxx, maxy = spec['bounds']
            
            # Extract the actual footprint of the vector dataset
            bounds = gdf.total_bounds
            
            # Snap the footprint outward to perfectly align with the absolute master grid intervals
            # We use floor() for minimums and ceil() for maximums to guarantee full encapsulation
            m_minx = minx + math.floor((bounds[0] - minx) / res) * res
            m_miny = miny + math.floor((bounds[1] - miny) / res) * res
            m_maxx = minx + math.ceil((bounds[2] - minx) / res) * res
            m_maxy = miny + math.ceil((bounds[3] - miny) / res) * res

            # Generate the 1D arrays for the grid lines
            x_edges = np.arange(m_minx, m_maxx, res)
            y_edges = np.arange(m_miny, m_maxy, res)
            
            polys, grid_ids = [], []
            width_cells = int(round((maxx - minx) / res))
            
            # Build the 2D polygon mesh and calculate the absolute 1D grid_id for each pixel
            for yi in y_edges:
                for xi in x_edges:
                    polys.append(box(xi, yi, xi + res, yi + res))
                    col = int((xi - minx) // res)
                    row = int((maxy - yi - res) // res) 
                    grid_ids.append((row * width_cells) + col)
                    
            return gpd.GeoDataFrame({'grid_id': grid_ids}, geometry=polys, crs=target_crs)

        # 4. Generate the Target Intersect Meshes
        poly_mesh = _build_mesh(poly_gdf, poly_grid_name)
        line_mesh = _build_mesh(line_gdf, line_grid_name)

        # 5. Parallel Execution Engine
        processed_fragments = []
        
        def _execute_parallel(target_gdf, target_mesh):
            """Internal orchestrator that splits data and manages the Process Pool."""
            if target_gdf.empty: return
            
            # Array Split divides the GeoDataFrame into roughly equal chunks based on n_jobs
            chunks = np.array_split(target_gdf, n_jobs)
            
            # ProcessPoolExecutor bypasses the Python GIL, spinning up separate OS-level processes
            with concurrent.futures.ProcessPoolExecutor(max_workers=n_jobs) as executor:
                # Dispatch the chunks to the static _overlay_worker
                futures = [
                    executor.submit(vector_spatial_engine._overlay_worker, chunk, target_mesh, parent_spec) 
                    for chunk in chunks if not chunk.empty
                ]
                # Gather the results as they finish processing
                for future in concurrent.futures.as_completed(futures):
                    try:
                        result = future.result()
                        if not result.empty:
                            processed_fragments.append(result)
                    except Exception as e:
                        if logger: logger.error(f"Worker failed during spatial overlay: {e}")

        # Dispatch the parallel jobs sequentially by geometry type
        if logger: logger.info("Dispatching Polygon overlay to parallel workers...")
        _execute_parallel(poly_gdf, poly_mesh)
        
        if logger: logger.info("Dispatching Line overlay to parallel workers...")
        _execute_parallel(line_gdf, line_mesh)

        # 6. Final Assembly
        # Stitch all the processed parallel chunks back into a single continuous DataFrame
        if processed_fragments:
            relational_fragments = pd.concat(processed_fragments, ignore_index=True)
            # Re-assert spatial context since pd.concat strips it
            relational_fragments = gpd.GeoDataFrame(relational_fragments, geometry='geometry', crs=target_crs)
        else:
            relational_fragments = gpd.GeoDataFrame()

        if logger: logger.info("Hierarchical vector normalization complete.")
        return relational_fragments, original_lookup_gdf